clearvars

%% Parameters
path    = "C:\database\raw\BerkeleyOutdoorWalk.db"

query   =  ...
    "SELECT * " + ...
    "FROM 'BerkeleyOutdoorWalk.Subject03.Binocular' " + ...
    "WHERE name GLOB '*Global.Pos[x-z]'" + ...
    "ORDER BY key";

out = Sqlite2Mat(path, query);